// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetConfigData, GetConfigResponses, GetCredentialsData, GetCredentialsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get API configuration
 *
 * Get configuration information for the API.
 */
export const getConfig = <ThrowOnError extends boolean = false>(options?: Options<GetConfigData, ThrowOnError>) => (options?.client ?? client).get<GetConfigResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/config',
    ...options
});

/**
 * Get credentials
 *
 * Get a list of credentials from all configured providers.
 */
export const getCredentials = <ThrowOnError extends boolean = false>(options?: Options<GetCredentialsData, ThrowOnError>) => (options?.client ?? client).get<GetCredentialsResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/credentials',
    ...options
});
