// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions } from '@tanstack/react-query';
import type { AxiosError } from 'axios';

import { client } from '../client.gen';
import { getConfig, getCredentials, type Options } from '../sdk.gen';
import type { GetConfigData, GetConfigResponse, GetCredentialsData, GetCredentialsResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getConfigQueryKey = (options?: Options<GetConfigData>) => createQueryKey('getConfig', options);

/**
 * Get API configuration
 *
 * Get configuration information for the API.
 */
export const getConfigOptions = (options?: Options<GetConfigData>) => queryOptions<GetConfigResponse, AxiosError<DefaultError>, GetConfigResponse, ReturnType<typeof getConfigQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getConfig({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getConfigQueryKey(options)
});

export const getCredentialsQueryKey = (options?: Options<GetCredentialsData>) => createQueryKey('getCredentials', options);

/**
 * Get credentials
 *
 * Get a list of credentials from all configured providers.
 */
export const getCredentialsOptions = (options?: Options<GetCredentialsData>) => queryOptions<GetCredentialsResponse, AxiosError<DefaultError>, GetCredentialsResponse, ReturnType<typeof getCredentialsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getCredentials({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCredentialsQueryKey(options)
});
